CREATE TABLE AUTH_AUTHORITY (
    id CHAR(36) PRIMARY KEY,
    roleCode VARCHAR(20) NOT NULL,
    roleDescription VARCHAR(100) NOT NULL,
    CONSTRAINT UK_AUTH_AUTHORITY_CODE UNIQUE (roleCode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE AUTH_USER_DETAILS (
    id CHAR(36) PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    created_on DATETIME NOT NULL,
    updated_on DATETIME NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone_number VARCHAR(255),
    provider VARCHAR(255),
    verification_code VARCHAR(255),
    enabled BOOLEAN DEFAULT FALSE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE AUTH_USER_AUTHORITY (
    user_id CHAR(36) NOT NULL,
    authority_id CHAR(36) NOT NULL,
    PRIMARY KEY (user_id, authority_id),
    FOREIGN KEY (user_id) REFERENCES AUTH_USER_DETAILS(id) ON DELETE CASCADE,
    FOREIGN KEY (authority_id) REFERENCES AUTH_AUTHORITY(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;